### ISSUE TITLE
Deprecate old npm packages

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero#50]
The old npm packages:
- https://www.npmjs.com/package/cicero-core
- https://www.npmjs.com/package/cicero-cli
- https://www.npmjs.com/package/cicero-engine
- https://www.npmjs.com/package/cicero-server
- https://www.npmjs.com/package/generator-cicero-template

should be deprecated and a notice added that references the new packages:
- https://www.npmjs.com/package/@accordproject/cicero-core
- https://www.npmjs.com/package/@accordproject/cicero-cli
- https://www.npmjs.com/package/@accordproject/cicero-engine
- https://www.npmjs.com/package/@accordproject/cicero-server
- https://www.npmjs.com/package/@accordproject/generator-cicero-template

**Comment by FelixKuehl** [comment]
+1 We were running into the same issue. Some docs (Getting started tutorial) still suggest to do `npm install -g cicero-cli` instead of `npm install -g @accordproject/cicero-cli`.
Doing so and attempting to run "cicero parse" on one of the example templates, results in the error _"/foo/cicero-template-library/src/helloworld" is not a valid cicero template. Make sure that package.json exists and that it has a engines.cicero entry._
This is quite misleading and took us a while to figure out that this was related to the incorrect version.

Also it should be pointed out, that it is necessary to install the exact version required by the template. In order to run the helloworld template we had to `npm install -g @accordproject/cicero-cli@0.4.4`

**Comment by FelixKuehl** [comment]
By the way, if the cicero-cli is not downwards compatible (Template with cicero version 0.4.4-0 can not be executed with cicero-cli 0.5.0), it should probably rather be template specific dependency instead of a global one. 
Shouldnt the cli be version independent and just delegate to the cicero engine that a template depends on localy (in its package.json) ? This would feel like a cleaner and less confusing pattern to me. Or am I missing something?

**Comment by mttrbrts** [comment]
Many thanks, @FelixKuehl, can you provide a link to the getting started tutorial that had the incorrect instruction, please? I'll make sure that it's updated.

Newer templates versions do include a semantic version which is checked by the template loader and you get a slightly better error message. The CLI does have a dependency on the `cicero-engine` version that matches, as you describe.

Unfortunately, the version tests are quite strict while we iterate towards a 1.0 release. i.e there are lots of changes that are not guaranteed to be backwards compatible. Generally, a minor version increment implies a breaking change for 0.x releases. From version 1.0 onwards we plan to adopt the following principle: 
- MAJOR version when we make incompatible API changes,
- MINOR version when we add functionality in a backwards-compatible manner, and
- PATCH version when we make backwards-compatible bug fixes.

This should make this issue less prevalent. This aligns with the Semantic Versioning system (https://semver.org/)

Unfortunately, it's not straightforward to delegate to the engine version that is specified by the template, as a template is not necessarily an npm package, even though it has a `package.json`! I'm open to suggestions on this.

The documentation could be clearer on these items, we'd be happy to accept a PR 😉 ?

The docs are at https://docs.accordproject.org, and built from the repo at https://github.com/accordproject/techdocs

**Comment by FelixKuehl** [comment]
Thanks @mttrbrts for clarification. I looked up the doc and it was actually not even explaining how to install the correct version of cicero-cli. Pull request is made: https://github.com/accordproject/techdocs/pull/10

**Comment by jeromesimeon** [comment]
Can we consider this closed?

**Comment by irmerk** [comment]
Following up on this issue being closed @dselman @mttrbrts @jeromesimeon

**Comment by jeromesimeon** [comment]
> Following up on this issue being closed @dselman @mttrbrts @jeromesimeon

The packages are owned by @dselman on NPMJS so I don't think it can be resolved by anyone else.

Sample commands for deprecating:
```
npm deprecate cicero-core "This package has been replaced by @accordproject/cicero-core"
```
