### ISSUE TITLE
Method for template signing and verification in Template class

### ISSUE THREAD

**Issue by sanketshevkar** [accordproject/cicero#671]
# Feature Request 🛍️

## Context

A method that will be used by template instances to sign the template markdown, logic and model.

## Detailed Description

Using crypto module from nodejs and node-forge library to execute this method. Use PKCS12 keystores to sign the contents. This method will be used in toArchive method. Users will pass the path to the PKCS12 keystore, password for the keystore as options to the toArchive method. From toArchive method the signTemplate method will be called. It will return the signature and it will be stored in the .cta archive.

**Comment by sanketshevkar** [comment]
@jerome does this format look good to you?

**Comment by jeromesimeon** [comment]
> @jerome does this format look good to you?

hi @sanketshevkar Looks like a good start! A few things that may help:
- a bit of a description for the user functionality (as a user I want to sign a contract because XXX to do YYY through API/through ...).
- related issues so we can keep track of how things connect. e.g., there is already an issue for signing templates #262 or #558

**Comment by sanketshevkar** [comment]
Thanks @jeromesimeon. I'll make these changes.
